create sequence if not exists application_number_seq start with 1000 increment by 1;

create table institution (
    id bigint generated by default as identity primary key,
    code varchar(40) not null unique,
    legal_name varchar(200) not null,
    trade_name varchar(200) not null,
    status varchar(30) not null,
    created_at timestamp with time zone not null
);

create table branch (
    id bigint generated by default as identity primary key,
    institution_id bigint not null,
    code varchar(40) not null,
    name varchar(120) not null,
    city varchar(120) not null,
    status varchar(30) not null,
    constraint fk_branch_institution foreign key (institution_id) references institution(id),
    constraint uk_branch_institution_code unique (institution_id, code)
);

create table user_account (
    id bigint generated by default as identity primary key,
    institution_id bigint null,
    branch_id bigint null,
    full_name varchar(180) not null,
    email varchar(180) not null unique,
    password_hash varchar(255) not null,
    role varchar(40) not null,
    status varchar(30) not null,
    created_at timestamp with time zone not null,
    constraint fk_user_institution foreign key (institution_id) references institution(id),
    constraint fk_user_branch foreign key (branch_id) references branch(id)
);

create table borrower (
    id bigint generated by default as identity primary key,
    institution_id bigint not null,
    document_type varchar(20) not null,
    document_number varchar(20) not null,
    legal_name varchar(200) not null,
    trade_name varchar(200),
    economic_activity varchar(200) not null,
    monthly_revenue numeric(18, 2) not null,
    status varchar(30) not null,
    created_at timestamp with time zone not null,
    constraint fk_borrower_institution foreign key (institution_id) references institution(id),
    constraint uk_borrower_institution_document unique (institution_id, document_number)
);

create table credit_product (
    id bigint generated by default as identity primary key,
    institution_id bigint not null,
    code varchar(40) not null,
    name varchar(180) not null,
    currency varchar(10) not null,
    min_amount numeric(18, 2) not null,
    max_amount numeric(18, 2) not null,
    min_term_months integer not null,
    max_term_months integer not null,
    annual_rate numeric(8, 4) not null,
    status varchar(30) not null,
    constraint fk_credit_product_institution foreign key (institution_id) references institution(id),
    constraint uk_credit_product_institution_code unique (institution_id, code)
);

create table credit_application (
    id bigint generated by default as identity primary key,
    application_number varchar(20) not null unique,
    institution_id bigint not null,
    branch_id bigint not null,
    borrower_id bigint not null,
    product_id bigint not null,
    requested_amount numeric(18, 2) not null,
    term_months integer not null,
    purpose varchar(500) not null,
    status varchar(40) not null,
    assigned_analyst_id bigint null,
    risk_assessment_id bigint null,
    committee_required boolean not null default false,
    approved_amount numeric(18, 2) null,
    rejection_reason varchar(500) null,
    created_by_user_id bigint not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    version bigint not null default 0,
    constraint fk_credit_application_institution foreign key (institution_id) references institution(id),
    constraint fk_credit_application_branch foreign key (branch_id) references branch(id),
    constraint fk_credit_application_borrower foreign key (borrower_id) references borrower(id),
    constraint fk_credit_application_product foreign key (product_id) references credit_product(id),
    constraint fk_credit_application_created_by foreign key (created_by_user_id) references user_account(id),
    constraint fk_credit_application_assigned_analyst foreign key (assigned_analyst_id) references user_account(id)
);

create table risk_assessment (
    id bigint generated by default as identity primary key,
    application_id bigint not null unique,
    institution_id bigint not null,
    score integer not null,
    risk_level varchar(20) not null,
    debt_to_income_ratio numeric(8, 4) not null,
    flags_json text,
    recommendation varchar(30) not null,
    assessed_by_user_id bigint not null,
    assessed_at timestamp with time zone not null,
    constraint fk_risk_assessment_application foreign key (application_id) references credit_application(id),
    constraint fk_risk_assessment_institution foreign key (institution_id) references institution(id),
    constraint fk_risk_assessment_user foreign key (assessed_by_user_id) references user_account(id)
);

create table approval_decision (
    id bigint generated by default as identity primary key,
    application_id bigint not null,
    institution_id bigint not null,
    decision varchar(20) not null,
    approved_amount numeric(18, 2) null,
    reason varchar(500) null,
    decided_by_user_id bigint not null,
    decided_at timestamp with time zone not null,
    decision_source varchar(20) not null,
    constraint fk_approval_decision_application foreign key (application_id) references credit_application(id),
    constraint fk_approval_decision_institution foreign key (institution_id) references institution(id),
    constraint fk_approval_decision_user foreign key (decided_by_user_id) references user_account(id)
);

create table disbursement_order (
    id bigint generated by default as identity primary key,
    application_id bigint not null,
    institution_id bigint not null,
    amount numeric(18, 2) not null,
    currency varchar(10) not null,
    destination_bank varchar(120) not null,
    destination_account varchar(120) not null,
    status varchar(20) not null,
    idempotency_key varchar(120) null,
    created_by_user_id bigint not null,
    executed_by_user_id bigint null,
    created_at timestamp with time zone not null,
    executed_at timestamp with time zone null,
    version bigint not null default 0,
    constraint fk_disbursement_order_application foreign key (application_id) references credit_application(id),
    constraint fk_disbursement_order_institution foreign key (institution_id) references institution(id),
    constraint fk_disbursement_order_created_by foreign key (created_by_user_id) references user_account(id),
    constraint fk_disbursement_order_executed_by foreign key (executed_by_user_id) references user_account(id)
);

create table idempotency_record (
    id bigint generated by default as identity primary key,
    institution_id bigint not null,
    idempotency_key varchar(120) not null,
    operation_type varchar(40) not null,
    resource_type varchar(60) not null,
    resource_id bigint not null,
    response_status varchar(30) not null,
    created_at timestamp with time zone not null,
    constraint fk_idempotency_institution foreign key (institution_id) references institution(id),
    constraint uk_idempotency_institution_key unique (institution_id, idempotency_key)
);

create table audit_entry (
    id bigint generated by default as identity primary key,
    institution_id bigint null,
    actor_user_id bigint null,
    action varchar(80) not null,
    entity_type varchar(80) not null,
    entity_id varchar(80) not null,
    previous_status varchar(40) null,
    new_status varchar(40) null,
    detail_json text not null,
    created_at timestamp with time zone not null,
    constraint fk_audit_institution foreign key (institution_id) references institution(id),
    constraint fk_audit_actor_user foreign key (actor_user_id) references user_account(id)
);
